### ISSUE TITLE
Falling Trees Distance Horizon Bug

### ISSUE THREAD

**Issue by BehradGamer13** [PandaMods-Dev/Pandas-Falling-Trees#84]
so I was testing a few mods and started having weird issues with Bambo. when I turned DH off the issue got fixed but I want to have a high render distance without actually changing my render Distance the settings render distance up
so please fix this bug
thanks.

**Comment by BehradGamer13** [comment]
![45d4f79c-5113-4c1c-8494-8043b6a87835-1711490523446](https://github.com/user-attachments/assets/6c18c362-0b07-4eec-8687-30ffc954c6b4)

**Comment by BehradGamer13** [comment]
![2024-07-15_14 37 06](https://github.com/user-attachments/assets/d7319688-b6f8-4125-aa7a-a1dc931f7f67)
![Uploading 2024-07-15_14.36.37.png…]()

**Comment by BaldrEldursson** [comment]
This is caused by DH because the LODs can't be smaller than a block.
Try going in the Distant Horizons settings -> Advanced options -> Graphics -> Advanced Graphics Options.
There you can increase Overdraw Prevention.
I think that should fix bamboo near you. Far away bamboo will still look a bit different with DH.

Hope this helps.

**Comment by ThePandaOliver** [comment]
As the person above explained, this is not caused by Falling trees.
Falling trees does not make any changes to blocks before they're mined.

**Comment by TomekGziut** [comment]
So is there any solution to thus problem?

**Comment by ThePandaOliver** [comment]
This is not an issue with Panda's Falling Trees, you will have to ask the creators of Distance Horizons to help you.
